#ifndef WebPages_h
    #define WebPages_h

    #include <WString.h>

    const String ROOT_PAGE = ""
        "<!DOCTYPE HTML>"
        "<html lang=\"en\">"
        "  <head>"
        "    <title>${rootWebTitle}</title>"
        "    <style>"
        "      table, th, td {border: 1px solid black; border-collapse: collapse;}"
        "      th, td {padding: 2px 10px;}"
        "      th {background-color: #DCDCDC}"
        "    </style>"
        "  </head>"
        "  <body>"
        "    <h1>Welcome to '${hostName}'!</h1>"
        "    <h2>Firmware Version: ${firmwareVersion}</h2>"
        "    <h3>Device Information:</h3>"
        "    <table>"
        "      <tr><th>Description</th><th>Value</th></tr>"
        "      <tr><td>Core Version</td><td>${coreVersion}</td></tr>"
        "      <tr><td>CPU Freq</td><td>${cpuFreq}MHz</td></tr>"
        "      <tr><td>Free Heap</td><td>${freeHeap}KB</td></tr>"
        "    </table>"
        "  </body>"
        "</html>"
    ;

    const String LOGIN_PAGE = ""
        "<!DOCTYPE HTML>"
        "<html lang=\"en\">"
        "  <head>"
        "    <title>Admin Login</title>"
        "    <style>"
        "      .info {background-color: #e7f3fe; border-left: 6px solid #2196F3;}"
        "    </style>"
        "  </head>"
        "  <body>"
        "    <div class=\"info\">"
        "      <p><strong>Info!</strong> This page is not functional in this firmware version!</p>"
        "    </div>"
        "    <form name=\"login\" method=\"post\" id=\"login\" action=\"admin\"> "
        "      Password: <input type=\"password\" name=\"adminpwd\" id=\"adminpwd\">"
        "      <br> "
        "      <button type=\"submit\">Submit</button> <a href='/'><h4>Home</h4></a>"
        "    </form>"
        "  </body>"
        "</html>"
    ;

    const String ADMIN_PAGE = ""
        "<!DOCTYPE HTML>"
        "<html lang=\"en\">"
        "  <head>"
        "    <title>Admin Page</title>"
        "  </head>"
        "  <body>"
        "    <form name=\"settings\" method=\"post\" id=\"settings\" action=\"admin\"> "
        "      <h2>AP WiFi Settings</h2>"
        "      <table>"
        "        <tr><td>SSID:</td><td><input maxlength=\"32\" type=\"text\" value=\"${ssid}\" name=\"ssid\" id=\"ssid\"></td></tr>"
        "        <tr><td>Password:</td><td><input maxlength=\"63\" type=\"text\" value=\"${pwd}\" name=\"pwd\" id=\"pwd\"></td></tr>"
        "      </table>"
        "      <h2>Local Network Settings</h2>"
        "      <table>"
        "        <tr><td>Hostname:</td><td></td></tr>"
        "        <tr><td>IP Address:</td><td></td></tr>"
        "        <tr><td>Subnet:</td><td></td></tr>"
        "        <tr><td>Gateway:</td><td></td></tr>"
        "      </table>"
        "      <h2>Device Settings</h2>"
         "      <table>"
        "        <tr><td>Serial Baud:</td><td></td></tr>"
        "        <tr><td>CPU Speed MHz:</td><td></td></tr>"
        "      </table>"
        "      <button type=\"submit\">Submit</button> <a href='/'><h4>Home Page</h4></a>"
        "    </form>"
        "  </body>"
        "</html>"
    ;

    const String NOT_FOUND_PAGE = ""
        "<!DOCTYPE HTML>"
        "<html lang=\"en\">"
        "  <head>"
        "    <title>404 NOT FOUND</title>"
        "  </head>"
        "  <body>"
        "    <h1>Ooops, You broke it!</h1>"
        "    Just kidding, Resource was not found!"
        "  </body>"
        "</html>"
    ;
#endif